name: CI

on: [pull_request, workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          repository: danioq/dnd-be
          tags: ${GITHUB_REF##*/}